### ISSUE TITLE
ERC6909X deadline nit

### ISSUE THREAD

**Issue by zobront** [frangio/erc6909-extensions#1]
Hey, obnoxiously small detail, but it looks like [in the EIP](https://github.com/frangio/ERCs/blob/erc6909x/ERCS/eip-xxxx.md#signatures) you write:

> deadline is a timestamp starting at which the signature MUST be rejected.

But [in the code](https://github.com/frangio/erc6909-extensions/blob/e6278e52e48cefe68367786316143c17cccfe57f/contracts/ERC6909X.sol#L76) you check:

`require(block.timestamp <= deadline, "expired sig");`

These treat the situation where `deadline == now` differently. It might be worth shifting one of them so they align.

**Comment by frangio** [comment]
Do you have an opinion about which one is more natural or better?

**Comment by frangio** [comment]
Also as a general note this repo has become slightly out of sync with the final spec.

Although the ambiguity you point out is present and should be fixed in the final spec, because one part says "deadline is a timestamp starting at which the signature MUST be rejected" and another says "checks that deadline is greater than or equal to the block timestamp".

**Comment by zobront** [comment]
I see `deadline == block.timestamp` being acceptable more frequently and think that's more intuitive.

As you said, the code also aligns with the description later in the spec. I'd recommend just changing the earlier line in the spec to:

> "deadline is a timestamp after which the signature MUST be rejected"

**Comment by frangio** [comment]
Fixed in https://github.com/frangio/ERCs/commit/4d765d71940db25a901a592a17aa8e2a16b6efd6. Thanks!
